dist: trusty

language: php

sudo: false

php:
    - 5.6
    - 7.0

env:
    global:
        - secure: "JOmze1vhktBd64PmXiSzU2a0IGnyOvBQU0oZhPF7crUtbPxoOt2Mjnl+4L54au7PY4gURxdOu2M3UfT3OqU6UIiKZhUCkJ24Yi67YbEuKRgtEYqZoca13SmBRZ+1fCP9ospAjHR6FshiauitFpI+2oUqyLL/9Ssj/jZYrbjXZ7PtjvgXUMNnF/qnQf0qdjbOhz9XhpRHzsjkZAzjUS4MUf7BdM+aL970nFJ619jPppucSObJp8pv1bDnm52W4jzyN1INDYgDtBualFF3tCmm+dwdVy+J8zjfoBp/XfqFU908LPhssPG6OwnO8mnvnXaQgVPS/aGBgXK9elSjC8oJufCtk5aO3SX5P+1WSGD47hK4AxMtF8K9oqPqOX/nRLHvHrgMERriaG9X6YAxbAO+9nEkKxTqJTFM1BfmEaDaAWBGfIrQxK25tAr5+tyqvuDplDGGgoYvGwAqOPdQK+v2NswYyKQs5+5W771uASHjihEXHMOCyh3CrLh1NloNwX4Eq3Iw3ikpy6b0CWB24DxtZ9E+EJNVyjl1a4xmFXFljXq6BVERbcKl55WLVlS3b3fdAeTkvNRsai6Chibjmpgc1mT2yAPmsk+LskxYszKOjHASlf8l4y6VgMn4BfypU8HU7aYtvmRf+80yi9M/8IsEEHT5qPW2OgzrYsg51NtHbjM="
        - secure: "kkNxzsgUU8T0njo35u0gQvsAL9x9yZUbXjkJnd50ca82hclSB+2oHTzdzOC+TVTjI96d/40eksPH4ThO4oGpFQvvMT3TTiRrBBNfdKqgnz6G9JAQjSoK/tftEZZJsbHJPLiFMAx24WOwBOt+TT7PaTS44HygVutOaTpn2ydNYtFJX/P4lJtjE4xJ3oWNzg4q3wk9cNHj/mJ7phZdRI2kY6rRmnleFAIzL/jUo1NF7Gp55VbL6ZCcyJo4WNFv/tLgdpIl9aN0ahWUSGMJ7V9aMME9CgKW87CKiPeTY5MW3875MMWpJK9oLE7gWSCiAbLy4fwhOtJvjrn3XFJCh1d2knI2oFnXigVUmHjLXTVe7v3go0fPVMIZnglfrqeCfwj1nEuZcTJaD7nZGFnPbFYaKS9nMLJE0j/Mevf0wQw0FzJIWoGKlnoET28miwilQGUqe5bkdnQNBs4Fudr6c24SomEYax9TuCwH0vbl4XP2oz3wVjzT3ZJcA3MaZjSK9t7GewE268j72T5lAOKXTHT/NHq/oN37WDMlUyU5HkDJ3SOhwg7wEktNWNaoftO9ebT+82NESG4x2hqAAl69R2BTHzhyj41VcdMekbV3J0Dz2FeFzXRu3LLLLfCwRShRrANWT2LpsekMSOCIEV1TR7gNdkKUvSr4IcpbBJrW7NAtNQk="
    matrix:
        - TEST_SUITE=unit
        - TEST_SUITE=static

matrix:
    exclude:
        - php: 7.0
          env: TEST_SUITE=static

cache:
    directories:
        - $HOME/.composer/cache

install:
    - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then echo '{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}' > auth.json; fi"
    - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then composer install --prefer-dist; fi"
    - sh -c "if [ '$TEST_SUITE' = 'static' ]; then npm install; fi"

script:
    - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then php vendor/bin/phpcs; fi"
    - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then php vendor/bin/phpmd Api/,Block/,Controller/,Model/,Observer/,Setup/ text cleancode,codesize,controversial,design,naming,unusedcode; fi"
    - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then php vendor/bin/phpcpd Api/ Block/ Controller/ Model/ Observer/ Setup/; fi"
    - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then php vendor/bin/phpunit --coverage-clover build/logs/clover.xml; fi"
    - sh -c "if [ '$TEST_SUITE' = 'static' ]; then ./node_modules/.bin/grunt ci; fi"

after_script:
    - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then php vendor/bin/coveralls; fi"
