dist: trusty

language: php

sudo: false

php:
    - 5.6
    - 7.0

env:
    global:
        - secure: "jnK3IkqxWd7T+Fo9zMXTI13ndLPD+0S8oEnO5DGC9kUQ9hWmf8RY/o7OFeSyY9VjftO0OGXDt94V2diuo0SEKtHdzpz57ShihsKzM0IUzvPrZkMNweiAGmAVJzp+l3UHXfUJocSo8KXPMQkXAG0MJsAlhrWWmBh0O6Kb4FQol6WBeXBfwHjM0MRPGAtZPX277BkbePmzsRJRt73/CrpPxg3V+LRXYmUwoKiQYj83YKfgcGCazJ8/9cjp3WrbCx/NwgiKhRABsUbQMJvFqBL4OiLRr0tx04OLmAZauTwkRRW61sY1cmdEMx9dL2hfmMP2beq9Hyz3aQ+lLV8hlnDAlWCSXleI+zieGcKFvz/gL2IE6LlEXWgA5kTTyxgKKdKm/wrZjBhxEGFOZn9SkQdcMNZrkvenEoJ8+u3xzKY/Ff9ReRwvqfct97RWviycTnoRm3ZtO4rk+HD/pB6JdUTaUeeyhJW8TJMOIUHBLfua2sy7kOuM4/MIxxAnudpTIOv+3VyoRtMVfE4YQN214DFRp3AqKQJiYFp18Y8QJeUm3p7NLaJNsf2Jvg+1cAdvfE36hRkR4kCcQzsgV67FUgUZi6JF+9salwVEOhnErDjEeH/vCwLiw+dwnJI52bMq2BGRmmwTgeA/+vmj7REi/jhwEqCzcFWqBMlQpgf0uRNqgMI="
        - secure: "gW+ZO2SRHLg1dhJjU6JOfPfwnaOA4upmBda5QbvMwSaq/ANJ+EiZOS/X4PRMwurKwaJeyHsZwhOSlcnwkraa7Wrro7VDwm2HImwn4gg3/vAVDwmuBozUvFPoUVEvxadlMJxhbn6cItn6SFwsDwh+8jQ7n8SMAoD31/67pYLnOEX2ECKkgmzB0u7YirvpRVdgatbT5a1lT3bW4zBmIEy1Uo0GmZ/TtJ8UmO8p7fqD7OtY5JSBT1EMAwwfhaepLLrL9M+NL2Eew7H8gshR4T8B+p5Np/vD2MdbrCIyYpNS3PpnDIKmxem3BCJhaje3XMVo/ef+mmegCdQ27E6AO9++T19H/jAEI7X/sona1SSNORUSfiwhPbZ/KK9wcu1fSAEe7LotV99EnV5YHyoG4mgIznQT6/hMvCZV60Fc/0U6OaEk+OCsCJZpnSOcW+cvn35QeGx1sNFsJH36nDsDD8UJUFcU7f4pRAWkB8/90ZlV5EtuVLakErp1Sd4CvadNSGNVpXkK+E79vjazZtekFb3mIEBInYVlbIOUWN+7GfucYMXicgAj7syPoo/BZFxcKUzYWy0IE8U8CMgc6oRV2OTXgGAGhmNRDn4iiJSrK2EtJobh+qFs+av6TX41NBAyf21gqQiqIs3LdzVNtrXvG3wBXwYHvk09jn8gLotWpiHjvbM="
    matrix:
        - TEST_SUITE=unit
        - TEST_SUITE=static

matrix:
    exclude:
        - php: 7.0
          env: TEST_SUITE=static

cache:
    directories:
        - $HOME/.composer/cache

install:
    - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then echo '{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}' > auth.json; fi"
    - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then composer install --prefer-dist; fi"
    - sh -c "if [ '$TEST_SUITE' = 'static' ]; then npm install; fi"

script:
    - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then php vendor/bin/phpcs; fi"
    - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then php vendor/bin/phpmd Api/,Block/,Controller/,Model/,Observer/,Setup/ text cleancode,codesize,controversial,design,naming,unusedcode; fi"
    - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then php vendor/bin/phpcpd Api/ Block/ Controller/ Model/ Observer/ Setup/; fi"
    - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then php vendor/bin/phpunit --coverage-clover build/logs/clover.xml; fi"
    - sh -c "if [ '$TEST_SUITE' = 'static' ]; then ./node_modules/.bin/grunt ci; fi"

after_script:
    - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then php vendor/bin/coveralls; fi"
