dist: trusty

language: php

sudo: false

php:
    - 5.6
    - 7.0

env:
    global:
        - secure: "K80pMNlmNKdRwWe9U/U0f9nTF7oBIJFIdR8iwceTsjSY+Nj43S5kFHgLtmvZDYYL2y9S6NsNGf0SXiWey4tt3xKV5pJVBFcJtjQTHlDCbXgHt+k3w1H5SxlxVlfKLfNqor11UZySuW+Z1V/1Tb9ATu4Xu/E/gKuSTDLTtR2gCTLZSZLVUjJJ0iJqsotUbs/AnqB+lKAUSZk4UbMaF0MmdXtUCk+38Oi1UAdz9s1t7syGcFJxTjiIiXO/xIr00UxLa7UmdRUzcSUMynosq0mAGmuoNnGN8LZcrpoeXAsB8Mpb5yEXzWBQqYLuvmr0cuFqN2B+dNOfzWqfViXRS1KftoUiU90JDyld0u1u1NdyNssSbM8z1Hkx6hJF2g1roRH9wgWNGlSYl9F7L9HJtJDY2wNx4poIY1+h2pqSZpoMJJqg2w644n+FvJt7e5O6YJJRcR2cANYWrP+EZF5qa9z5fAZRN0ydogVSLmIv4uOlUT0hZwJg0FOHUGzcl1xGsSeqrTF7RTkkPkgqUoO5fQ+nuW/A8F6NT86aRX76ILF2oEFsSfJjveJFBDXWnspnwGOJRHbQKO3Ey2cFTYm6phy0PUF+KFn1zp7Cx5Nt1CbnFosWXHd90rJF51KHc6OJGtlHoDiyBLxEZEiMwZEmBB7pinkR6G12pu9x+W6w/eRFxuQ="
        - secure: "d593PrIQDJ5anCUOXa81Ri2JOwwANvgg5lqo5L30u42WwPBKFEQ+z5890fysVgaOxYOMYOBnVilHGN4u2ucKf6QzALd01UMg6jmV0GGfsz9c4VFdaxDQjrVapmbO1+u9TWXxaynfYZ48YK1NcTIZECEECVewc0x0zMRRnCHD1Sd1AXF+2Q9voPMPNjgZTZ25psoYpQBHUNPNGfJJ03A9S24ys458x9JYIOKHZ4ivWfT7zx52u+OA7n3LMCIfRVhquqT66ijR4TjyYb9rqbJLfIOeFkopiWEbbHvhTPxJqCXLk9tOrOykg+q67cEV0F485HjCeyAXQvC4MVGDVlnHLJXN9kgtVwnL2X4zV+Dvwt2J5jBve9/OeYmqPP+5yvJI4ZGugaElfrRIIWrE+4WCET+cACHPdqQ6OHe+5Vl9mHp44dPbFNqX+yc9waiRrMbL26IxFgyMRqC3QfQmSHPL391KWB3AeExqDoLkrnb9eRzpK9IWKKgC6462e7IJisVhX83eR1r5qhDeace+d1cXUrGuFMUQun6qVgM/cATjDeSd7T6BXGEHwYrUGcpR1lbHRH0gKJL+N9jfyjtBn+ONhTYIucyGRh0N63iSLOuA+md6OXADtG0oTxwRswGF++ZMSHXhmyKw13qBj5q2Yr+aGbbKjgLRsnGw2GYySfWzCi8="
    matrix:
        - TEST_SUITE=unit
        - TEST_SUITE=static

matrix:
    exclude:
        - php: 7.0
          env: TEST_SUITE=static

cache:
    directories:
        - $HOME/.composer/cache

install:
    - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then echo '{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}' > auth.json; fi"
    - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then composer install --prefer-dist; fi"
    - sh -c "if [ '$TEST_SUITE' = 'static' ]; then npm install; fi"

script:
    - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then php vendor/bin/phpcs; fi"
    - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then php vendor/bin/phpmd Api/,Block/,Controller/,Model/,Observer/,Setup/ text cleancode,codesize,controversial,design,naming,unusedcode; fi"
    - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then php vendor/bin/phpcpd Api/ Block/ Controller/ Model/ Observer/ Setup/; fi"
    - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then php vendor/bin/phpunit --coverage-clover build/logs/clover.xml; fi"
    - sh -c "if [ '$TEST_SUITE' = 'static' ]; then ./node_modules/.bin/grunt ci; fi"

after_script:
    - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then php vendor/bin/coveralls; fi"
