dist: trusty

language: php

sudo: false

php:
    - 5.6
    - 7.0

env:
    global:
        - secure: "U8b8NFbzfslySBMgaRoXnUF6Sy12J9griusxQsxLhR6cobPjUcsrbs4+t8nXiuIDtgHrwm+RLJT0vH0vAqC0T3YTBnrr3qLRpni0hlcyf94N57VJrgc/WDciwMbGkQ2lTZeZQa9SJU9fUJ7ZjqC0t6pnXrnW2V7EfYVDgSncvP33Z+bCCP6bNtIkJuF200lZyCGhAv+LrKhQhw4HzSvmlXOz6vCBJR7/O2hriRywAuVDsuDHo3vYRKj6L0sH1bQxLPh1eQZO46AgJoJLQDjGlAchcIUhOyxkOUF0E+AMUL6xGSjXfp+oX6Y9Tg4pyWZvbS21vgefLo5B+PMNCAJRHDqI4op0jRT9QiQ3HaUW/+28EUV5J54pyo0spm5KApIY1Em+MGiN1+UVMh9jzP67gspYon4cJHSSJrKPZb7CzgMqS8v0c/6zPbhVjkUWQ1rMqCTR64AutIVeQZvvK5KBnMjrpQd/7+A9/RBpWQGXsY3/AxM7mLX5emAKkhnejYioWTgNThr8fLntCDqA1Kg0L0q+o4RPQWUOuIQHxTWp4FP0Mwlx5tmo3ZDIdJFVbixQUW3hiG4RjaL3fUEd5ajNmBXtFk3Fse2ehrw5GInoTR09KagLcWJ3Ta7VvXgtRHNChnwN+zMdAOak1ldWkIu3RTrm75yWbbe48S2vWZE+MVs="
        - secure: "fi3Wg8dmDUts9gLag+pTXAIZ4q4qtSr4+rB/5Fpah4OopBuK9CRfe26+KiFiH1FP2GDBMaurbRUmr9K+Q6wfLLIGNJ8HD0cRffMgOEW3JYOGv6VDQm0X6Bs77lrS027NE6gUi9kSW6zRry79rBrTFERY/tWBXeZgvN3Z6M9ZLFK56tYugVH6ubHq27O+gSWF435P9MmgM0WOnfhebmBybFuNKYlSNRCqS10VoCdZfEdDLPABpR+GUHp9ix/2eeOPKd2JD1lNBHqA4q32omzrh/YxxxpcpGHZxvUL6Undcoy+uXfQ4oywSmN16PjP/gtceJNSejYBChxyCtyBSm2Daw9D3lINIFSKZRi9ES6yJUHyOjQAgHqPcrV/W2qaWj3GWF4GhwiW99+pWWewLspjZ5F1BbxU5y6SQS1i5FfQSuiXViUwoTo72GuEAFf8/CD/Y4XDgC9nscmWF1tbnlx/fr9js6/Gg4NHEO2QoqL3qTYhPC3eXtEcqYWMuG6zSGhfZThJUC2CiaQOjt0nGs6PZDpxd87bBX6f31ofSFgr9F8pWtv0x0o9BFEx/J9MTpvo1AZh2pYwZB6z6cB7rcrgCbjg7grzM4U07EHgva1ggsSIDdJAUIe1WbV6eD5i8PCImLGpCv97b6etfEYW1mbKqUG4zZM6hM6zM7B34np7rfI="
    matrix:
        - TEST_SUITE=unit
        - TEST_SUITE=static

matrix:
    exclude:
        - php: 7.0
          env: TEST_SUITE=static

cache:
    directories:
        - $HOME/.composer/cache

install:
    - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then echo '{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}' > auth.json && cat auth.json; fi"
    - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then composer install --prefer-dist; fi"
    - sh -c "if [ '$TEST_SUITE' = 'static' ]; then npm install; fi"

script:
    - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then php vendor/bin/phpcs; fi"
    - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then php vendor/bin/phpmd Api/,Block/,Controller/,Model/,Observer/,Setup/ text cleancode,codesize,controversial,design,naming,unusedcode; fi"
    - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then php vendor/bin/phpcpd Api/ Block/ Controller/ Model/ Observer/ Setup/; fi"
    - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then php vendor/bin/phpunit --coverage-clover build/logs/clover.xml; fi"
    - sh -c "if [ '$TEST_SUITE' = 'static' ]; then ./node_modules/.bin/grunt ci; fi"

after_script:
    - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then php vendor/bin/coveralls; fi"
